name: RasterTiles
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - gdal
  - geopy
  - matplotlib
  - numpy
  - pandas
  - folium
  - waitress
  - pillow
  - flask
  - geotiff
  - pip
  - bokeh
  - vega_datasets